import { Task, TimeLog } from "@/features/kanban/api";
import { Paper } from "@/app/mock-tests/_components/types";
import { Post } from "@/features/posts/api";
import { BuddyRecommendation } from "@/features/profile/api";

export const MOCK_TOUR_TASKS: Task[] = [
    {
        id: "mock-task-1",
        title: "Indian Polity: Fundamental Rights & Duties (Laxmikanth Ch 7-11)",
        subject: "Polity",
        priority: "HIGH",
        status: "DONE",
        type: "REVISION",
        estimated_hours: 3,
        description: "Completed notes revision and solved 45 PYQs.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-2",
        title: "Modern History: Spectrum Chapter 14 - National Movement",
        subject: "History",
        priority: "HIGH",
        status: "IN_PROGRESS",
        type: "READING",
        estimated_hours: 2.5,
        description: "Reading Gandhi Irwin pact and Round table conferences.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-3",
        title: "CSAT Paper-II: Speed Math, Permutation & Reading Comprehension",
        subject: "CSAT",
        priority: "MEDIUM",
        status: "IN_PROGRESS",
        type: "PRACTICE",
        estimated_hours: 2,
        description: "Targeting 25 accuracy questions.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-4",
        title: "Macroeconomics: Monetary Policy & Inflation Trends (NCERT Class 12)",
        subject: "Economy",
        priority: "LOW",
        status: "TODO",
        type: "READING",
        estimated_hours: 3,
        description: "RBI repo rate mechanisms and liquidity adjustment facility.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-5",
        title: "Ethics Case Studies: Conflict of Interest & Probity in Governance",
        subject: "Ethics",
        priority: "MEDIUM",
        status: "DONE",
        type: "PRACTICE",
        estimated_hours: 2,
        description: "Drafted 4 case study answers with stakeholder frameworks.",
        created_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_PAPERS: Paper[] = [
    {
        id: "mock-paper-1",
        filename: "UPSC Prelims GS-1 Full Mock Paper 01",
        exam_name: "UPSC CSE 2025",
        target_exam: "UPSC CSE",
        exam_type: "full",
        q_count: 100,
        duration: 120,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "mock-paper-2",
        filename: "CSAT Paper-II Speed Test Series",
        exam_name: "UPSC CSAT",
        target_exam: "UPSC CSE",
        exam_type: "practice",
        q_count: 80,
        duration: 120,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "mock-paper-3",
        filename: "Economy & Current Affairs Topic Booster",
        exam_name: "Economy Special",
        target_exam: "All Exams",
        exam_type: "practice",
        q_count: 50,
        duration: 60,
        uploaded_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_POSTS: Post[] = [
    {
        id: "mock-post-1",
        title: "UPSC 2024 Board Interview Transcript: Board of Ms. Preeti Sudan",
        content: "Detailed transcript of my board interview held on 24th April. Duration was 35 mins with extensive questions on administrative ethics, solar mission, and tribal development schemes in Odisha...",
        tags: ["Interview", "UPSC", "Transcripts"],
        upvotes: 84,
        comment_count: 26,
        like_count: 84,
        bookmark_count: 31,
        created_at: new Date().toISOString(),
        user: {
            username: "Anonymous_Aspirant",
        },
    },
    {
        id: "mock-post-2",
        title: "How I consolidated Modern Indian History in 5 concise charts",
        content: "Sharing my handwritten one-page mindmaps for Governor Generals, revolutionary movements, and Congress sessions from 1885 to 1947. Useful for quick 10-minute revision before mocks.",
        tags: ["Notes", "History", "Mindmaps"],
        upvotes: 142,
        comment_count: 38,
        like_count: 142,
        bookmark_count: 59,
        created_at: new Date().toISOString(),
        user: {
            username: "HistoryGeek_99",
        },
    },
    {
        id: "mock-post-3",
        title: "Best approach to eliminate options in UPSC Prelims Polity questions?",
        content: "Whenever questions have 'Always', 'Only', or 'Shall be final', what is your mental checklist to avoid trick traps? Would love insights from veterans.",
        tags: ["Polity", "Strategy", "PYQs"],
        upvotes: 57,
        comment_count: 19,
        like_count: 57,
        bookmark_count: 14,
        created_at: new Date().toISOString(),
        user: {
            username: "PolityPrep2025",
        },
    },
];

export const MOCK_TOUR_TIME_LOGS: TimeLog[] = [
    {
        id: "mock-log-1",
        task_id: "mock-task-1",
        user_id: "demo-user",
        duration_minutes: 180,
        note: "Completed Laxmikanth revision",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-2",
        task_id: "mock-task-2",
        user_id: "demo-user",
        duration_minutes: 120,
        note: "Spectrum national movement notes",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-3",
        task_id: "mock-task-3",
        user_id: "demo-user",
        duration_minutes: 90,
        note: "CSAT comprehension practice",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-4",
        task_id: "mock-task-5",
        user_id: "demo-user",
        duration_minutes: 110,
        note: "Ethics case study drafting",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_RECS: BuddyRecommendation[] = [
    {
        id: "mock-rec-1",
        username: "Aspirant_Delhi",
        bio: "Full-time UPSC aspirant targeting GS-2 & Optional PSIR.",
        target_exam: "UPSC CSE 2025",
        district: "Central Delhi",
        state: "Delhi",
        distance_range: "5 km",
        mutual_count: 3,
        score: 95,
        match_reasons: ["same_exam", "dist:5 km", "active"],
    },
    {
        id: "mock-rec-2",
        username: "CivilAspirant_RJ",
        bio: "Geography optional. Early morning 5 AM study club member.",
        target_exam: "UPSC CSE 2025",
        district: "Jaipur",
        state: "Rajasthan",
        distance_range: "State",
        mutual_count: 2,
        score: 88,
        match_reasons: ["same_exam", "active"],
    },
    {
        id: "mock-rec-3",
        username: "Banker_Pune",
        bio: "Practicing Quant & Reasoning mocks daily.",
        target_exam: "SBI PO / RBI Grade B",
        district: "Pune",
        state: "Maharashtra",
        distance_range: "City",
        mutual_count: 1,
        score: 80,
        match_reasons: ["same_exam"],
    },
];
