import { Task, TimeLog } from "@/features/kanban/api";
import { Paper } from "@/app/mock-tests/_components/types";
import { Post } from "@/features/posts/api";
import { BuddyRecommendation } from "@/features/profile/api";

export const MOCK_TOUR_TASKS: Task[] = [
    {
        id: "mock-task-1",
        title: "Physics: Rotational Dynamics & Center of Mass (HC Verma Ch 10)",
        subject: "Physics",
        priority: "HIGH",
        status: "IN_PROGRESS",
        type: "PRACTICE",
        estimated_hours: 3,
        description: "Solving 30 PYQs from JEE Main & Advanced archive.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-2",
        title: "Biology: Molecular Basis of Inheritance & Lac Operon (NCERT Ch 6)",
        subject: "Biology",
        priority: "HIGH",
        status: "DONE",
        type: "REVISION",
        estimated_hours: 2.5,
        description: "NCERT line-by-line reading and labeled diagram practice for NEET.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-3",
        title: "Indian Polity: Fundamental Rights & Judicial Review (Laxmikanth Ch 7-11)",
        subject: "Polity",
        priority: "MEDIUM",
        status: "DONE",
        type: "READING",
        estimated_hours: 3,
        description: "Drafted notes on landmark SC judgements & Article 32.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-4",
        title: "Quantitative Aptitude: High-Level Bar Graph & Pie Chart DI",
        subject: "Aptitude",
        priority: "HIGH",
        status: "TODO",
        type: "PRACTICE",
        estimated_hours: 2,
        description: "Targeting 20 speed arithmetic sets for SBI PO / RBI Grade B.",
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-task-5",
        title: "General English: Subject-Verb Agreement & Error Spotting Rules",
        subject: "English",
        priority: "LOW",
        status: "TODO",
        type: "REVISION",
        estimated_hours: 1.5,
        description: "100 golden grammar rules for SSC CGL Tier-1.",
        created_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_PAPERS: Paper[] = [
    {
        id: "guest-paper-jee",
        filename: "JEE Main Physics & Mathematics Grand Mock 01",
        exam_name: "JEE Main 2025",
        target_exam: "JEE Main",
        exam_type: "full",
        q_count: 10,
        duration: 30,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-neet",
        filename: "NEET UG Biology & Chemistry Speed Booster 01",
        exam_name: "NEET UG 2025",
        target_exam: "NEET",
        exam_type: "full",
        q_count: 10,
        duration: 25,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-upsc",
        filename: "UPSC Prelims GS-1 Full Mock Paper 01",
        exam_name: "UPSC CSE 2025",
        target_exam: "UPSC CSE",
        exam_type: "full",
        q_count: 10,
        duration: 20,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-bank",
        filename: "Banking Quantitative Aptitude & Reasoning Mock 01",
        exam_name: "SBI PO / IBPS PO",
        target_exam: "Banking",
        exam_type: "practice",
        q_count: 10,
        duration: 20,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-ssc",
        filename: "SSC CGL Tier-1 General Awareness & English Booster",
        exam_name: "SSC CGL 2025",
        target_exam: "SSC",
        exam_type: "practice",
        q_count: 10,
        duration: 15,
        uploaded_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_POSTS: Post[] = [
    {
        id: "mock-post-1",
        title: "How I boosted Physics from 45 to 88 marks in JEE Main 2024",
        content: "Detailed breakdown of chapter-wise question weightage in JEE Main Physics. Focusing heavily on Modern Physics, Thermodynamics, and Current Electricity gave the highest ROI in the final 60 days.",
        tags: ["JEE", "Physics", "IIT-JEE"],
        upvotes: 182,
        comment_count: 42,
        like_count: 182,
        bookmark_count: 75,
        created_at: new Date().toISOString(),
        user: { username: "IIT_Aspirant_2025" },
    },
    {
        id: "mock-post-2",
        title: "NCERT Biology chapter-wise high-yield flowcharts for 350+ in NEET UG",
        content: "Compiled 15 one-page summary flowcharts for Genetics, Plant Physiology, and Human Reproduction directly from NCERT lines. Essential for quick revision during the last week before mock exams.",
        tags: ["NEET", "Biology", "Medical"],
        upvotes: 215,
        comment_count: 53,
        like_count: 215,
        bookmark_count: 94,
        created_at: new Date().toISOString(),
        user: { username: "DoctorAspirant_NEET" },
    },
    {
        id: "mock-post-3",
        title: "UPSC 2024 Board Interview Transcript: Board of Ms. Preeti Sudan",
        content: "Detailed transcript of my board interview held on 24th April. Duration was 35 mins with extensive questions on administrative ethics, solar mission, and tribal development schemes in Odisha...",
        tags: ["UPSC", "Interview", "Polity"],
        upvotes: 94,
        comment_count: 28,
        like_count: 94,
        bookmark_count: 41,
        created_at: new Date().toISOString(),
        user: { username: "Anonymous_Aspirant" },
    },
];

export const MOCK_TOUR_TIME_LOGS: TimeLog[] = [
    {
        id: "mock-log-1",
        task_id: "mock-task-1",
        user_id: "demo-user",
        duration_minutes: 180,
        note: "Solved HC Verma Rotational Dynamics",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-2",
        task_id: "mock-task-2",
        user_id: "demo-user",
        duration_minutes: 120,
        note: "NCERT Genetics revision",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-3",
        task_id: "mock-task-3",
        user_id: "demo-user",
        duration_minutes: 90,
        note: "Laxmikanth Fundamental Rights",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: "mock-log-4",
        task_id: "mock-task-4",
        user_id: "demo-user",
        duration_minutes: 110,
        note: "Banking DI speed drills",
        logged_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
];

export const MOCK_TOUR_RECS: BuddyRecommendation[] = [
    {
        id: "mock-rec-1",
        username: "IIT_Aspirant_Kota",
        bio: "Targeting JEE Advanced 2025. Daily 8-hour study streak member.",
        target_exam: "JEE Main & Advanced",
        district: "Kota",
        state: "Rajasthan",
        distance_range: "5 km",
        mutual_count: 4,
        score: 96,
        match_reasons: ["same_exam", "active_streak"],
    },
    {
        id: "mock-rec-2",
        username: "DoctorAspirant_AIIMS",
        bio: "Full-time NEET UG aspirant. Solving 150 biology/chemistry MCQs daily.",
        target_exam: "NEET (UG)",
        district: "Central Delhi",
        state: "Delhi",
        distance_range: "City",
        mutual_count: 3,
        score: 92,
        match_reasons: ["same_exam", "active"],
    },
    {
        id: "mock-rec-3",
        username: "CivilAspirant_Delhi",
        bio: "UPSC CSE 2025 aspirant with PSIR optional.",
        target_exam: "UPSC CSE",
        district: "Old Rajinder Nagar",
        state: "Delhi",
        distance_range: "City",
        mutual_count: 2,
        score: 88,
        match_reasons: ["same_exam", "active"],
    },
    {
        id: "mock-rec-4",
        username: "Banker_Bangalore",
        bio: "Practicing Quant & Reasoning speed mocks daily for SBI PO / RBI Grade B.",
        target_exam: "Banking (SBI/IBPS/RBI)",
        district: "Bangalore",
        state: "Karnataka",
        distance_range: "State",
        mutual_count: 1,
        score: 85,
        match_reasons: ["same_exam"],
    },
];
