export const MOCK_GUEST_POSTS = [
    {
        id: "guest-post-1",
        title: "How I boosted Physics from 45 to 88 marks in JEE Main 2024",
        content: "Detailed breakdown of chapter-wise question weightage in JEE Main Physics. Focusing heavily on Modern Physics, Thermodynamics, and Current Electricity gave the highest ROI in the final 60 days.",
        tags: ["JEE", "Physics", "IIT-JEE"],
        upvotes: 182,
        comment_count: 42,
        like_count: 182,
        bookmark_count: 75,
        created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
        user: { username: "IIT_Aspirant_2025" },
    },
    {
        id: "guest-post-2",
        title: "NCERT Biology chapter-wise high-yield flowcharts for 350+ in NEET UG",
        content: "Compiled 15 one-page summary flowcharts for Genetics, Plant Physiology, and Human Reproduction directly from NCERT lines. Essential for quick revision during the last week before mock exams.",
        tags: ["NEET", "Biology", "Medical"],
        upvotes: 215,
        comment_count: 53,
        like_count: 215,
        bookmark_count: 94,
        created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
        user: { username: "DoctorAspirant_NEET" },
    },
    {
        id: "guest-post-3",
        title: "UPSC 2024 Board Interview Transcript: Board of Ms. Preeti Sudan",
        content: "Detailed transcript of my board interview held on 24th April. Duration was 35 mins with extensive questions on administrative ethics, solar mission, and tribal development schemes in Odisha...",
        tags: ["UPSC", "Interview", "Polity"],
        upvotes: 94,
        comment_count: 28,
        like_count: 94,
        bookmark_count: 41,
        created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
        user: { username: "Anonymous_Aspirant" },
    },
    {
        id: "guest-post-4",
        title: "30-Day High-Level Data Interpretation & Puzzle Roadmap for SBI PO Mains",
        content: "A day-by-day practice schedule for Caselet DIs, Missing DIs, and Variable-based Circular Seating Arrangements. Includes accuracy tracking metrics and time limits.",
        tags: ["Banking", "SBI-PO", "Aptitude"],
        upvotes: 118,
        comment_count: 22,
        like_count: 118,
        bookmark_count: 56,
        created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
        user: { username: "BankingPro_2025" },
    },
    {
        id: "guest-post-5",
        title: "SSC CGL 100 Golden Grammar Rules & Error Spotting Cheat Sheet",
        content: "Summary of frequently repeated error spotting patterns in SSC CGL Tier-1 & Tier-2 exams: Subject-Verb Agreement, Inversion, Conditionals, and Prepositional phrases.",
        tags: ["SSC", "English", "Grammar"],
        upvotes: 87,
        comment_count: 16,
        like_count: 87,
        bookmark_count: 38,
        created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
        user: { username: "SSC_Officer_Prep" },
    },
];

export const MOCK_GUEST_EXPERIENCES = [
    {
        id: "guest-exp-1",
        exam_name: "JEE Advanced 2024",
        year: 2024,
        verdict: "Selected (AIR 342 - IIT Bombay)",
        difficulty: "Hard",
        description: "Dropper year strategy: Focused on solving previous 10 years JEE Advanced papers twice. Giving weekly 6-hour full mocks in the exact 9-12 and 2:30-5:30 slots built mental stamina.",
        is_anonymous: false,
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
        user_id: "demo-jee",
    },
    {
        id: "guest-exp-2",
        exam_name: "NEET UG 2024",
        year: 2024,
        verdict: "Selected (Score 685/720 - AIIMS)",
        difficulty: "Hard",
        description: "Read NCERT Biology 12 times. For Physical Chemistry, made a separate formula book with 20 solved examples per chapter. Daily 180 questions timed mock test in April.",
        is_anonymous: false,
        created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
        user_id: "demo-neet",
    },
    {
        id: "guest-exp-3",
        exam_name: "UPSC CSE 2024",
        year: 2024,
        verdict: "Selected (Rank 142)",
        difficulty: "Hard",
        description: "Cleared in 3rd attempt with Anthropology optional. Daily 6-hour pomodoro study and writing 2 answers daily post-Prelims was the game changer.",
        is_anonymous: false,
        created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
        user_id: "demo-upsc",
    },
    {
        id: "guest-exp-4",
        exam_name: "SBI PO 2024",
        year: 2024,
        verdict: "Selected (Probationary Officer)",
        difficulty: "Moderate",
        description: "Cracked in 1st attempt. Speed math tricks for Prelims and reading daily editorial summaries for Descriptive English and General Banking Awareness.",
        is_anonymous: true,
        created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
        user_id: "demo-bank",
    },
];

export const MOCK_GUEST_PAPERS = [
    {
        id: "guest-paper-jee",
        filename: "JEE Main Physics & Mathematics Grand Mock 01",
        exam_name: "JEE Main 2025",
        target_exam: "JEE Main",
        exam_type: "full",
        q_count: 10,
        duration: 30,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-neet",
        filename: "NEET UG Biology & Chemistry Speed Booster 01",
        exam_name: "NEET UG 2025",
        target_exam: "NEET",
        exam_type: "full",
        q_count: 10,
        duration: 25,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-upsc",
        filename: "UPSC Prelims GS-1 Full Mock Paper 01",
        exam_name: "UPSC CSE 2025",
        target_exam: "UPSC CSE",
        exam_type: "full",
        q_count: 10,
        duration: 20,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-bank",
        filename: "Banking Quantitative Aptitude & Reasoning Mock 01",
        exam_name: "SBI PO / IBPS PO",
        target_exam: "Banking",
        exam_type: "practice",
        q_count: 10,
        duration: 20,
        uploaded_at: new Date().toISOString(),
    },
    {
        id: "guest-paper-ssc",
        filename: "SSC CGL Tier-1 General Awareness & English Booster",
        exam_name: "SSC CGL 2025",
        target_exam: "SSC",
        exam_type: "practice",
        q_count: 10,
        duration: 15,
        uploaded_at: new Date().toISOString(),
    },
];

export const MOCK_GUEST_QUESTIONS_MAP: Record<string, any[]> = {
    "guest-paper-jee": [
        {
            is_passage: false,
            questions: [
                {
                    id: "jee-q1",
                    question_text: "A particle of mass m moves under the action of a central force where potential energy is U(r) = k * r^2 / 2. If the particle moves in a circular orbit of radius R, what is its speed?",
                    type: "mcq",
                    topic: "Physics - Mechanics",
                    difficulty: "Medium",
                    explanation: "For central force, F = -dU/dr = -k*r. Setting centripetal force m*v^2 / R = k*R gives v = R * sqrt(k/m).",
                    options: [
                        { id: "j1", option_text: "R * sqrt(k / m)", is_correct: true },
                        { id: "j2", option_text: "sqrt(k / (2 * m * R))", is_correct: false },
                        { id: "j3", option_text: "R * sqrt(2 * k / m)", is_correct: false },
                        { id: "j4", option_text: "sqrt(k * R / m)", is_correct: false },
                    ],
                },
                {
                    id: "jee-q2",
                    question_text: "What is the value of the integral ∫ (sin x / (sin x + cos x)) dx from 0 to π/2?",
                    type: "mcq",
                    topic: "Mathematics - Calculus",
                    difficulty: "Easy",
                    explanation: "Using property ∫_0^a f(x) dx = ∫_0^a f(a-x) dx: Adding both gives 2I = ∫_0^(π/2) 1 dx = π/2 => I = π/4.",
                    options: [
                        { id: "j5", option_text: "π / 2", is_correct: false },
                        { id: "j6", option_text: "π / 4", is_correct: true },
                        { id: "j7", option_text: "1", is_correct: false },
                        { id: "j8", option_text: "π / 8", is_correct: false },
                    ],
                },
                {
                    id: "jee-q3",
                    question_text: "Which of the following carbocations is the most stable?",
                    type: "mcq",
                    topic: "Chemistry - Organic",
                    difficulty: "Easy",
                    explanation: "Tropylium cation (cycloheptatrienyl cation) is aromatic with 6 π electrons conforming to Huckel's (4n+2) rule, making it exceptionally stable.",
                    options: [
                        { id: "j9", option_text: "Tert-butyl carbocation", is_correct: false },
                        { id: "j10", option_text: "Tropylium carbocation", is_correct: true },
                        { id: "j11", option_text: "Benzyl carbocation", is_correct: false },
                        { id: "j12", option_text: "Allyl carbocation", is_correct: false },
                    ],
                },
            ],
        },
    ],
    "guest-paper-neet": [
        {
            is_passage: false,
            questions: [
                {
                    id: "neet-q1",
                    question_text: "In a dihybrid cross between two heterozygous parents (AaBb x AaBb), what fraction of the offspring is expected to be homozygous for both dominant traits (AABB)?",
                    type: "mcq",
                    topic: "Biology - Genetics",
                    difficulty: "Easy",
                    explanation: "Probability of AA = 1/4 and BB = 1/4. Probability of AABB = (1/4) * (1/4) = 1/16.",
                    options: [
                        { id: "n1", option_text: "1 / 16", is_correct: true },
                        { id: "n2", option_text: "9 / 16", is_correct: false },
                        { id: "n3", option_text: "3 / 16", is_correct: false },
                        { id: "n4", option_text: "1 / 4", is_correct: false },
                    ],
                },
                {
                    id: "neet-q2",
                    question_text: "During which phase of meiosis do homologous chromosomes separate while sister chromatids remain associated at their centromeres?",
                    type: "mcq",
                    topic: "Biology - Cell Division",
                    difficulty: "Medium",
                    explanation: "In Anaphase I of Meiosis I, homologous chromosome pairs separate to opposite poles, while sister chromatids remain attached at the centromere until Anaphase II.",
                    options: [
                        { id: "n5", option_text: "Metaphase I", is_correct: false },
                        { id: "n6", option_text: "Anaphase I", is_correct: true },
                        { id: "n7", option_text: "Anaphase II", is_correct: false },
                        { id: "n8", option_text: "Telophase I", is_correct: false },
                    ],
                },
                {
                    id: "neet-q3",
                    question_text: "Which of the following pairs of compounds are functional isomers?",
                    type: "mcq",
                    topic: "Chemistry - Organic",
                    difficulty: "Easy",
                    explanation: "Ethanol (CH3CH2OH) and Dimethyl ether (CH3OCH3) have the same molecular formula C2H6O but different functional groups (alcohol vs ether).",
                    options: [
                        { id: "n9", option_text: "Ethanol and Dimethyl ether", is_correct: true },
                        { id: "n10", option_text: "Propan-1-ol and Propan-2-ol", is_correct: false },
                        { id: "n11", option_text: "n-Butane and Isobutane", is_correct: false },
                        { id: "n12", option_text: "Acetone and Acetaldehyde", is_correct: false },
                    ],
                },
            ],
        },
    ],
    "guest-paper-upsc": [
        {
            is_passage: false,
            questions: [
                {
                    id: "upsc-q1",
                    question_text: "With reference to the Constitution of India, which of the following is NOT a Fundamental Duty under Article 51A?",
                    type: "mcq",
                    topic: "Polity",
                    difficulty: "Medium",
                    explanation: "Voting in public elections was recommended by Swaran Singh Committee but was NOT included in Article 51A Fundamental Duties.",
                    options: [
                        { id: "u1", option_text: "To safeguard public property and abjure violence", is_correct: false },
                        { id: "u2", option_text: "To vote in general public elections", is_correct: true },
                        { id: "u3", option_text: "To develop scientific temper, humanism and spirit of inquiry", is_correct: false },
                        { id: "u4", option_text: "To uphold and protect the sovereignty, unity and integrity of India", is_correct: false },
                    ],
                },
                {
                    id: "upsc-q2",
                    question_text: "Consider the following statements regarding the Governor's Ordinance Making Power:\n1. The Governor can promulgate ordinances only when the Legislative Assembly is not in session.\n2. An ordinance has the same force and effect as an Act of the State Legislature.\nWhich of the statements given above is/are correct?",
                    type: "mcq",
                    topic: "Polity",
                    difficulty: "Hard",
                    explanation: "Under Article 213, both statements are correct. Governor can issue ordinance when legislature is in recess.",
                    options: [
                        { id: "u5", option_text: "1 only", is_correct: false },
                        { id: "u6", option_text: "2 only", is_correct: false },
                        { id: "u7", option_text: "Both 1 and 2", is_correct: true },
                        { id: "u8", option_text: "Neither 1 nor 2", is_correct: false },
                    ],
                },
            ],
        },
    ],
    "guest-paper-bank": [
        {
            is_passage: false,
            questions: [
                {
                    id: "bank-q1",
                    question_text: "A person travels from city A to city B at 60 km/h and returns from B to A at 40 km/h. What is the average speed of the whole journey?",
                    type: "mcq",
                    topic: "Quantitative Aptitude",
                    difficulty: "Easy",
                    explanation: "Average speed for equal distance = 2*x*y / (x+y) = 2*60*40 / (100) = 4800 / 100 = 48 km/h.",
                    options: [
                        { id: "b1", option_text: "50 km/h", is_correct: false },
                        { id: "b2", option_text: "48 km/h", is_correct: true },
                        { id: "b3", option_text: "45 km/h", is_correct: false },
                        { id: "b4", option_text: "52 km/h", is_correct: false },
                    ],
                },
                {
                    id: "bank-q2",
                    question_text: "In a certain code language, if 'BANK' is coded as '32' and 'PO' is coded as '31', how will 'EXAM' be coded?",
                    type: "mcq",
                    topic: "Reasoning",
                    difficulty: "Medium",
                    explanation: "E=5, X=24, A=1, M=13. Sum = 5 + 24 + 1 + 13 = 43.",
                    options: [
                        { id: "b5", option_text: "41", is_correct: false },
                        { id: "b6", option_text: "43", is_correct: true },
                        { id: "b7", option_text: "45", is_correct: false },
                        { id: "b8", option_text: "39", is_correct: false },
                    ],
                },
            ],
        },
    ],
    "guest-paper-ssc": [
        {
            is_passage: false,
            questions: [
                {
                    id: "ssc-q1",
                    question_text: "Which article of the Constitution of India guarantees the Right to Constitutional Remedies?",
                    type: "mcq",
                    topic: "General Awareness",
                    difficulty: "Easy",
                    explanation: "Article 32 guarantees the Right to Constitutional Remedies, famously called the 'Heart and Soul of the Constitution' by Dr. B.R. Ambedkar.",
                    options: [
                        { id: "s1", option_text: "Article 21", is_correct: false },
                        { id: "s2", option_text: "Article 32", is_correct: true },
                        { id: "s3", option_text: "Article 19", is_correct: false },
                        { id: "s4", option_text: "Article 14", is_correct: false },
                    ],
                },
            ],
        },
    ],
};

export const MOCK_GUEST_INSIGHTS = {
    total_attempts: 5,
    avg_score_pct: 82.0,
    best_score_pct: 90.0,
    total_papers_attempted: 4,
    recent_trend: [
        { exam_name: "JEE Main Physics & Math 01", percentage: 80.0, score: 80, max_score: 100, attempted_at: new Date(Date.now() - 86400000 * 6).toISOString() },
        { exam_name: "NEET UG Biology & Chemistry 01", percentage: 85.0, score: 85, max_score: 100, attempted_at: new Date(Date.now() - 86400000 * 4).toISOString() },
        { exam_name: "UPSC CSE GS-1 Full Mock 01", percentage: 74.0, score: 74, max_score: 100, attempted_at: new Date(Date.now() - 86400000 * 2).toISOString() },
        { exam_name: "Banking Quant & Reasoning 01", percentage: 90.0, score: 90, max_score: 100, attempted_at: new Date().toISOString() },
    ],
    per_paper: [
        { exam_name: "JEE Main Physics & Math 01", attempts: 2, best_pct: 88.0, avg_pct: 84.0, last_attempted_at: new Date().toISOString() },
        { exam_name: "NEET UG Biology & Chemistry 01", attempts: 1, best_pct: 85.0, avg_pct: 85.0, last_attempted_at: new Date(Date.now() - 86400000 * 4).toISOString() },
        { exam_name: "UPSC CSE GS-1 Full Mock 01", attempts: 1, best_pct: 74.0, avg_pct: 74.0, last_attempted_at: new Date(Date.now() - 86400000 * 2).toISOString() },
        { exam_name: "Banking Quant & Reasoning 01", attempts: 1, best_pct: 90.0, avg_pct: 90.0, last_attempted_at: new Date().toISOString() },
    ],
};
